version: "3.7"

services:

  traefik:
    command:
      # Exposes Traefik dashboard
      # (comment this to avoid useless security risks)
      - "--api.dashboard=true"

      # Docker Integration
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"

      # Entry Points
      - "--entrypoints.http80.address=:80"
    volumes:
      - ${CODE_SERVER_CWD}/data/letsencrypt:/letsencrypt
      - ${CODE_SERVER_CWD}/data/.htpasswd:/basic-auth/.htpasswd
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: traefik:v2.2
    network_mode: host
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.csi.loadbalancer.server.port=1337"
      - "traefik.http.routers.csi-traefik--80.rule=Host(`127.0.0.11`)"
      
      - "traefik.http.routers.csi-traefik--80.entrypoints=http80"
      - "traefik.http.routers.csi-traefik--80.service=api@internal"
      - "traefik.http.routers.csi-traefik--80.middlewares=csi-auth-passwd,csi-traefik-stripprefix"
      - "traefik.http.routers.csi-traefik--80.rule=Host(`${CODE_SERVER_DNS}`) && (PathPrefix(`/traefik`) || PathPrefix(`/api`))"
  
      - "traefik.http.middlewares.csi-basic-auth.basicauth.usersfile=/basic-auth/.htpasswd"
      # - "traefik.http.middlewares.csi-auth-passwd.forwardauth.address=http://${CODE_SERVER_IPv4_LOCAL}:40003"
      - "traefik.http.middlewares.csi-auth-passwd.forwardauth.address=https://api-alpha.dbox.zone/api/v1/auth/self"
      - "traefik.http.middlewares.csi-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.csi-redirect.redirectscheme.permanent=true"
      - "traefik.http.middlewares.csi-traefik-stripprefix.stripprefix.prefixes=/traefik"

  # auth-passwd:
  #   image: marcopeg/auth-passwd:0.0.9
  #   restart: always
  #   volumes:
  #     - ${CODE_SERVER_CWD}/data/passwd:/passwd
  #   environment:
  #     - "PORT=40003"
  #     - "BASE_URL=https://${CODE_SERVER_DNS}"
  #     - "COOKIE_DOMAIN=${CODE_SERVER_DNS}"
  #     - "COOKIE_SECRET=${CODE_SERVER_MGM_COOKIE_SECRET:-}"
  #   network_mode: host
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.csi-auth-passwd.loadbalancer.server.port=40003"

  #     # Configure basic HTTP mapping:
  #     - "traefik.http.routers.csi-auth--80.entrypoints=http80"
  #     - "traefik.http.routers.csi-auth--80.rule=Host(`${CODE_SERVER_DNS}`)"
  #     # - "traefik.http.routers.csi-auth--80.middlewares=csi-redirect"
  #     - "traefik.http.routers.csi-auth--80.rule=Host(`${CODE_SERVER_DNS}`) && PathPrefix(`/`)"

  code-server:
    image: marcopeg/nginx-proxy:0.0.2
    environment:
     - NGINX_PORT=40002
     - NGINX_UPSTREAM_PORT=40001
    network_mode: host
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.csi-code-server.loadbalancer.server.port=40002"
      - "traefik.http.routers.csi-code-server--80.entrypoints=http80"
      # - "traefik.http.routers.csi-code-server--80.middlewares=csi-redirect"
      - "traefik.http.routers.csi-code-server--80.rule=Host(`${CODE_SERVER_DNS}`)"
      - "traefik.http.routers.csi-code-server--80.middlewares=csi-auth-passwd"

  filebrowser:
    image: filebrowser/filebrowser:v2.10.0
    volumes:
      - /home/ubuntu:/srv
    command:
      - "--baseurl=/filebrowser"
      - "--noauth"
    labels:
      - "traefik.enable=true"

      # Configure basic HTTP mapping
      - "traefik.http.routers.csi-filebrowser--80.entrypoints=http80"
      - "traefik.http.routers.csi-filebrowser--80.middlewares=csi-redirect"
      - "traefik.http.routers.csi-filebrowser--80.middlewares=csi-auth-passwd"
      - "traefik.http.routers.csi-filebrowser--80.rule=Host(`${CODE_SERVER_DNS}`) && PathPrefix(`/filebrowser`)"

  netdata:
    labels:
      - "traefik.enable=true"

      # Configure basic HTTP mapping
      - "traefik.http.routers.csi-netdata--80.entrypoints=http80"
      - "traefik.http.routers.csi-netdata--80.middlewares=csi-redirect"
      - "traefik.http.routers.csi-netdata--80.rule=Host(`${CODE_SERVER_DNS}`)"
      - "traefik.http.routers.csi-netdata--443.middlewares=csi-auth-passwd,csi-netdata--stripprefix"

      # Configure Middlewares
      - "traefik.http.middlewares.csi-netdata--stripprefix.stripprefix.prefixes=/netdata"
    image: netdata/netdata:v1.26.0
    hostname: ${CODE_SERVER_DNS}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      # @TODO: map to local data folder
      # - netdataconfig:/etc/netdata
      # - netdatalib:/var/lib/netdata
      # - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
